name: CD - Deploy

on:
  workflow_run:
    workflows: ["CI - Build & Push Images"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug
        run: |
          docker --version
          docker compose version

      - name: Deploy
        run: |
          docker compose pull
          docker compose up -d
