name: CD - Deploy

on:
  workflow_run:
    workflows: ["CI - Build & Push Images"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show Debug
        run: |
          pwd
          ls -la

      - name: Deploy containers
        run: |
          docker compose pull
          docker compose up -d
