name: CD - Deploy

on:
  workflow_run:
    workflows: ["CI - Build & Push Images"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull images
        run: docker compose pull

      - name: Restart containers
        run: docker compose up -d
